{
 "title": "Futel Shit",
 "time": { "from": "now-5d", "to": "now" },
 "panels": [
  {
   "title": "Microcosm events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({label=\"futel-events\"} |= `PJSIP-445` | json | drop batch, channel, label, timestamp | event != `contact-status-Avail` [$__auto])"
    }
   ]
  },
  {
   "title": "Events (not contact-status-Avail)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({label=\"futel-events\"} |= `` | json \n| label_format chan=`{{ Replace .channel \"PJSIP-\" \"\" -1 }}` | label_format chan=`{{ .chan | replace \"445\" \"microcosm\"}}` | label_format chan=`{{ .chan | replace \"416\" \"breckenridge-pers\"}}` | label_format chan=`{{ .chan | replace \"410\" \"central\"}}` | label_format chan=`{{ .chan | replace \"615\" \"robotron\"}}` | label_format chan=`{{ .chan | replace \"655\" \"taylor\"}}` | label_format chan=`{{ .chan | replace \"695\" \"eighth\"}}` | label_format chan=`{{ .chan | replace \"620\" \"sowester\"}}` | label_format chan=`{{ .chan | replace \"625\" \"upright\"}}` | label_format chan=`{{ .chan | replace \"415\" \"breckenridge\"}}` | label_format chan=`{{ .chan | replace \"640\" \"alley27\"}}` | label_format chan=`{{ .chan | replace \"630\" \"ypsi\"}}` | label_format chan=`{{ .chan | replace \"680\" \"ainsworth\"}}` | label_format chan=`{{ .chan | replace \"405\" \"saratoga\"}}` \n| event != `contact-status-Avail` | __error__=`` | drop Time,batch,channel,label,timestamp,event [$__auto])"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({label=\"futel-events\"} |= `` | json channel=\"channel\", event=\"event\" | label_format chan=`{{ Replace .channel \"PJSIP-\" \"\" -1 }}` | label_format chan=`{{ .chan | replace \"445\" \"microcosm\"}}` | label_format chan=`{{ .chan | replace \"410\" \"central\"}}` | label_format chan=`{{ .chan | replace \"615\" \"robotron\"}}` | label_format chan=`{{ .chan | replace \"655\" \"taylor\"}}` | label_format chan=`{{ .chan | replace \"695\" \"eighth\"}}` | label_format chan=`{{ .chan | replace \"620\" \"sowester\"}}` | label_format chan=`{{ .chan | replace \"625\" \"upright\"}}` | label_format chan=`{{ .chan | replace \"415\" \"breckenridge\"}}` | label_format chan=`{{ .chan | replace \"640\" \"alley27\"}}` | label_format chan=`{{ .chan | replace \"630\" \"ypsi\"}}` | label_format chan=`{{ .chan | replace \"680\" \"ainsworth\"}}` | label_format chan=`{{ .chan | replace \"405\" \"saratoga\"}}` | event != `contact-status-Avail` | drop timestamp, label, event, batch, channel | __error__=`` [1h])"
    }
   ]
  },
  {
   "title": "pretty points",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count by(channel) (rate({label=\"futel-events\"} |= `` | json event=\"event\", channel=\"channel\" | event != `contact-status-Avail` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({label=\"futel-events\"} |= `` | json event=\"event\", channel=\"channel\" | event != `contact-status-Avail` | label_format chan=`{{ Replace .channel \"PJSIP-\" \"\" -1 }}` | label_format chan=`{{ .chan | replace \"445\" \"microcosm\"}}` | label_format chan=`{{ .chan | replace \"410\" \"central\"}}` | label_format chan=`{{ .chan | replace \"615\" \"robotron\"}}` | label_format chan=`{{ .chan | replace \"655\" \"taylor\"}}` | label_format chan=`{{ .chan | replace \"695\" \"eighth\"}}` | label_format chan=`{{ .chan | replace \"620\" \"sowester\"}}` | label_format chan=`{{ .chan | replace \"625\" \"upright\"}}` | label_format chan=`{{ .chan | replace \"415\" \"breckenridge\"}}` | label_format chan=`{{ .chan | replace \"640\" \"alley27\"}}` | label_format chan=`{{ .chan | replace \"630\" \"ypsi\"}}` | label_format chan=`{{ .chan | replace \"680\" \"ainsworth\"}}` | label_format chan=`{{ .chan | replace \"405\" \"saratoga\"}}` | drop timestamp, batch, channel, event, label | __error__=`` [$__auto])"
    }
   ]
  },
  {
   "title": "outgoing shit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(rate({label=\"futel-events\"} | json | event =~ `outgoing.*` | __error__=`` [1h]))"
    }
   ]
  }
 ]
}