name: Build and publish the web UI to gh-pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-web-ui:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
      working-directory: ./web
    - name: build web ui
      run: npm run build
      working-directory: ./web
    - name: commit updated data
      uses: EndBug/add-and-commit@v7
      with:
        add: 'dist'
        cwd: './web'
        branch: 'gh-pages'
        message: 'published web ui to gh-pages'
        pathspec_error_handling: exitImmediately
