name: Build and publish the web UI to gh-pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-web-ui:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
      working-directory: ./web
    - name: build web ui
      run: npm run build
      working-directory: ./web
    - name: checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
    - name: copy build output to gh-pages
      run: |
        rsync -avv web/dist/ gh-pages/
    - name: commit updated data
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        cwd: './gh-pages'
        # branch: 'gh-pages'
        message: 'publishing web ui to gh-pages'
        pathspec_error_handling: exitImmediately
